Feature/server
zenitheesc/serverd pull request #1
Opened 2021-09-23 02:36 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [X] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Base do servidor, agora é esperar as outras partes fazerem o trabalho para depois juntar tudo.

# Testing

Pra rodar é só usar o cmake, o programa aceita dois argumentos opcionais, o IP e a porta, por default ele vai usar o lacalhost e a porta 8080.

2021-09-23 11:50 UTC, mairacanal requested changes
Vai precisar passar um linting no código inteiro. Tirando isso, por entanto, está ok.

2021-09-23 11:50 UTC, mairacanal commented on src/server.cpp
> +            std::cout << e.what() << std::endl;
O que aconteceu com a indentação aqui?

2021-09-23 21:28 UTC, Grillo-0 commented on src/server.cpp
> +            std::cout << e.what() << std::endl;
Boa pergunta, agora com o formatter isso vai ser resolvido

2021-09-28 11:40 UTC, mairacanal approved these changes

2021-09-29 22:54 UTC, merged