Feature/bytes
zenitheesc/serverd pull request #14
Opened 2021-10-29 20:25 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [X] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Mudado a mensagem de string para bytes
# Testing
Rodar os testes unitários

Closes #12

2021-10-29 23:31 UTC, mairacanal requested changes
O preenchimento da mensagem com lixo até dar 26 bytes já está nesse PR?

2021-10-29 23:31 UTC, mairacanal commented on src/message-buffer.cpp
> +    Message messageObj(26);
Podia criar uma macro com o 26

2021-10-29 23:31 UTC, mairacanal commented on src/server.cpp
> +        buffer.write(receivedJson["equipe"], receivedJson["payload"]);
Podia extrair as strings "equipe" e "payload" em uma constante

2021-10-30 02:56 UTC, Math-42 commented on src/message-buffer.cpp
> +    m_currSize += sizeof(T);
Não poderia inverter essa lógica evitando o if praticamente vazio?
```suggestion
    if (m_currSize + sizeof(T) <= m_maxSize) {
        T value = json;
        std::memcpy(m_message.data() + m_currSize, &value, sizeof(T));
        m_currSize += sizeof(T);
    }
    
```

2021-10-30 02:56 UTC, Math-42 commented on src/message-buffer.cpp
> +    m_currSize += value.size();
Mesma coisa que disse anteriormente, creio que poderia inverter a lógica e não usar o return.

2021-10-31 02:02 UTC, Grillo-0 commented on src/message-buffer.cpp
> +    Message messageObj(26);
vc diria num arquivo de configs? Ai acessaria pelo configHandler?

2021-10-31 02:08 UTC, Grillo-0 commented on src/server.cpp
> +        buffer.write(receivedJson["equipe"], receivedJson["payload"]);
Vc diz assim ?
```suggestion
        std::string idKey = "equipe";
        std::string payloadKey = "payload";
        buffer.write(receivedJson[idKey], receivedJson[payloadKey]);
```

2021-10-31 02:08 UTC, Grillo-0 commented on src/message-buffer.cpp
> +    m_currSize += value.size();
Resolvi os dois

2021-10-31 11:50 UTC, mairacanal commented on src/server.cpp
> +        buffer.write(receivedJson["equipe"], receivedJson["payload"]);
Eu colocaria como constexp na classe inteira

2021-11-02 17:27 UTC, mairacanal commented on src/server.cpp
> +        buffer.write(receivedJson["equipe"], receivedJson["payload"]);
Considerando que constexp não é possível com string, pode-se colocar como const.

2021-11-03 21:12 UTC, mairacanal approved these changes

2021-11-03 21:12 UTC, merged