Feature/template
zenitheesc/serverd pull request #17
Opened 2021-11-25 02:52 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [X] ✨ Feature
- [ ] 🐞 Bug Correction
- [X] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Adiciona o template novo. 
Eu coloquei tudo que tem no template, queria saber se acham bom colocar tudo mesmo.
 
# Testing

Compilar o código e rodar o ctest

2021-11-27 17:06 UTC, mairacanal reviewed
É realmente necessário ter coisa de Vcpkg?

2021-11-28 07:28 UTC, CarlosCraveiro reviewed
Acho que daria para retirar algumas coisas do CMake, como a presença do Conan caso ja for possível utilizar o CMake sem ele. Havia feito um comentário antes, mass depois percebi que as linhas apagadas do Conan eram referentes ao CMake antigo então não sei se o Serverd ainda precisa do conan ou não. Porém, não acho que seria muito produtivo ir enxugando o template até ele ficar o mais mínimo possível, por isso, acredito que o CMake esteja ok.

Assim, pontuo só a remoção dos arquivos ``.yml`` referentes a Windows e Mac do ``.github\workflow\`` , visto que até onde estou recordado o servidor precisa do DBus p rodar, não tendo sido projetado para rodar nesses dois sistemas, portanto acho que não faz muito sentido ter esses arquivos no repositório.

Por último uma pergunta: esse pull request deveria ser no Serverd msm? Pq ele sobrescreve o README padrão do Zenith que está na develop com o README do template.

2021-11-29 14:05 UTC, Grillo-0 commented
> Acho que daria para retirar algumas coisas do CMake, como a presença do Conan caso ja for possível utilizar o CMake sem ele. Havia feito um comentário antes, mass depois percebi que as linhas apagadas do Conan eram referentes ao CMake antigo então não sei se o Serverd ainda precisa do conan ou não. Porém, não acho que seria muito produtivo ir enxugando o template até ele ficar o mais mínimo possível, por isso, acredito que o CMake esteja ok.
> 
> Assim, pontuo só a remoção dos arquivos `.yml` referentes a Windows e Mac do `.github\workflow\` , visto que até onde estou recordado o servidor precisa do DBus p rodar, não tendo sido projetado para rodar nesses dois sistemas, portanto acho que não faz muito sentido ter esses arquivos no repositório.
> 
> Por último uma pergunta: esse pull request deveria ser no Serverd msm? Pq ele sobrescreve o README padrão do Zenith que está na develop com o README do template.

Vou tirar o connan sim, bem lembrado de tirar o .yml de windows e mac pra esse projeto, não tinha me atentado a isso.

Eu fiquei nesse duvida se eu deixava o README do template do zenith ou o do novo, acho que vou juntar os dois colocando a tag de que todos os teste passaram

2021-11-29 14:05 UTC, Grillo-0 commented
> É realmente necessário ter coisa de Vcpkg?

não mesmo, vou tirar aqui

2021-11-29 14:45 UTC, mairacanal approved these changes

2021-11-29 16:57 UTC, CarlosCraveiro approved these changes

2021-11-30 20:01 UTC, Math-42 requested changes
Está ótimo, apenas duas observações, esses arquivos de template, como issue e pull request, são necessários? Outro ponto é, de fato não precisamos do conan e dos outros gerenciadores, mas seria interessante termos eles no nosso template padrão.

2021-12-03 03:03 UTC, Grillo-0 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Add any other context about the problem here.
Eu achei um template legal de pull request mas se achar de mais eu tiro. Eu também não pretendo tirar o Conan do template original

2022-02-15 16:58 UTC, merged