Feature/readme
zenitheesc/serverd pull request #21
Opened 2022-02-15 21:57 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [X] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:
Adiciona os passos para buildar e rodar o projeto e também como contribuir para o projeto

# Testing

2022-02-16 13:05 UTC, mairacanal requested changes

2022-02-16 13:05 UTC, mairacanal commented on README.md
> +    <a href="#how-to-contribute">How to contribute?</a>
Não precisava ter tirado os dots, eles ficam bonitos.

2022-02-16 13:05 UTC, mairacanal commented on README.md
> +To build the project run these steps
Antes de falar isso, poderia falar que tem que instalar as bibliotecas.

2022-02-16 13:05 UTC, mairacanal commented on README.md
> +Feel free to make issues and pull requests
```suggestion
We love when new people come and help us to improve our software! If you want to contribute to this project, check our Projects board and pick an idea to develop. When you finish coding, make a clear and descriptive pull request explaining your modifications.

If you find any sort of problem or have a suggestion to the project, please write an issue and we will be pleased to help you!
```

2022-02-16 13:05 UTC, mairacanal commented
Além disso, a badge do Ubuntu tá muito feia.

2022-02-16 17:13 UTC, Math-42 requested changes
Se a ideia desse readme for aquela que te falei de fazer a release, adicione um ou falando que a pessoa não precisa compilar e pode apenas baixar o executável que está disponível, além disso seria interessante ter esse readme em português visto que é para a olimpiada e para tirar dúvidas dos participantes.

2022-02-16 17:13 UTC, Math-42 commented on README.md
> +To build the project run these steps
Poderia ensinar a instalar o curl também

2022-02-21 22:18 UTC, mairacanal requested changes
Coloca ponto final e dois pontos no final das frases.

2022-02-21 22:18 UTC, mairacanal commented on README.md
> +You can either download the binary on the [Releases section](https://github.com/zenitheesc/serverd/releases), or you can build the project following the steps bellow
```suggestion
You can either download the binary on the [Releases section](https://github.com/zenitheesc/serverd/releases), or you can build the project following the steps below.
```

2022-02-21 22:18 UTC, mairacanal commented on README.md
> +First you need to install the necessary dependencies, on ubuntu you can install with this command
First, you need to install the necessary dependencies. On Debian based systems, you can install them with the following command:

2022-02-21 22:18 UTC, mairacanal commented on README.md
> +[Versão em Portguês](README.pt.md)
Centralizar isso aqui.

2022-02-23 21:04 UTC, mairacanal approved these changes

2022-02-23 21:14 UTC, merged