message-buffer: add getCurrMessage()
zenitheesc/serverd pull request #22
Opened 2022-02-21 02:20 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [X] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Adiciona a funcionalidade te obter a mensagem que vai ser enviada

2022-02-21 15:35 UTC, Math-42 requested changes

2022-02-21 17:57 UTC, Grillo-0 commented on src/message-buffer.cpp
> +    return json;
seria legal, mas acho que isso caberia num pull request separado

2022-02-21 22:01 UTC, mairacanal requested changes

2022-02-21 22:01 UTC, mairacanal commented on src/message-buffer.cpp
> +    return json;
Creio que nós já tentamos usar condition variable, mas, por algum motivo, não deu certo no passado (não lembro o motivo).

2022-02-22 18:30 UTC, Grillo-0 commented on src/message-buffer.cpp
> +    , m_currMessage { 26 }
verdade, mas é melhor eu fazer isso num PR separado, né?

2022-02-22 19:43 UTC, mairacanal commented on src/message-buffer.cpp
> +    , m_currMessage { 26 }
Pode ser sim

2022-02-22 19:44 UTC, mairacanal approved these changes

2022-02-23 23:24 UTC, Math-42 commented on src/message-buffer.cpp
> +    return json;
Acho que realmente não usamos direito, pelo o que vi ela realmente seria o ideal para o caso, mas de fato cabe em um pull request separado trocar todos mutex para variável condicionado.

2022-02-23 23:24 UTC, Math-42 approved these changes

2022-02-23 23:25 UTC, merged