Feature/fkd integration
zenitheesc/serverd pull request #28
Opened 2022-04-15 19:08 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [X] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Finalmente chegou a integração com o Frameworkd, assim terminando ~eu espero~ o serverd :)

# Testing

Para conseguir rodar o servidor é preciso colocar a .conf presente na pasta `config-files` em `/etc/dbus-1/system.d` e estar no diretório `config-files` onde está o `serverd.json`

Closes #8

2022-04-18 19:46 UTC, Math-42 approved these changes

2022-04-19 11:17 UTC, mairacanal requested changes

2022-04-19 11:17 UTC, mairacanal commented on src/server.cpp
> +    httplib::Server svr;
Não seria `m_svr` para seguir o padrão de nomenclatura?

2022-04-19 11:17 UTC, mairacanal commented on src/server.cpp
> +    ServerdService serverdService(host, port, "serverd");
```suggestion
    Daemon serverd{"serverd.json"};
    ServerdService serverdService{host, port, "serverd"};
```

2022-04-19 11:17 UTC, mairacanal commented on src/server.cpp
> +    }
```suggestion
    explicit ServerdService(const char* host, const int port)
        : RoutineService { "serverd" }
        , m_host { host }
        , m_port { port }
        , m_buffer { 10 }
    {
    }
```

2022-06-29 16:33 UTC, mairacanal requested changes
LGTM

2022-06-29 16:33 UTC, mairacanal commented on src/server.cpp
> +        , m_buffer { 10 }
Podia ser uma constante, ao invés de um magic number

2022-07-07 20:42 UTC, merged