message-buffer: fix: change getCurrMessage() behavior
zenitheesc/serverd pull request #29
Opened 2022-07-13 05:05 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [ ] ✨ Feature
- [X] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

On the previous way m_currMessage pointed to the latest message sent to
the server, now it's point to the first message sent that was not
already read.

2022-07-13 11:41 UTC, mairacanal requested changes

2022-07-13 11:41 UTC, mairacanal commented on src/message-buffer.hpp
Se você apagou a função `read()`, você pode apagar esse protótipo também.

2022-07-13 11:41 UTC, mairacanal commented on src/message-buffer.cpp
> +        json["data"];
O que isso tá fazendo?

2022-07-13 11:41 UTC, mairacanal commented on src/message-buffer.cpp
> +    std::cout << static_cast<int>(m_currMessage->first) << " : " << json << std::endl;
Vai ficar esse `std::cout` aqui mesmo?

2022-07-13 11:41 UTC, mairacanal commented on src/message-buffer.hpp
>      std::unique_ptr<std::thread> m_thread;
Você ainda está usando esse ponteiro?

2022-07-29 15:01 UTC, Grillo-0 commented on src/message-buffer.cpp
> +        json["data"];
Para converter pra BSON o json tem que ter alguma tag, como n tem nehuma menagem pra enviar eu só envio uma tag vazia

2022-07-29 21:17 UTC, Math-42 approved these changes
Eu aprovo, o único detalhe foi aquilo que já disse dos couts.

2022-07-29 21:39 UTC, merged