server: correct json received by the BIPS framework
zenitheesc/serverd pull request #33
Opened 2022-07-30 08:50 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [ ] ✨ Feature
- [X] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

O BIPS envia um json mal formatado, esse PR corrige a mensagem recebida antes de parsear para JSON, isso sem interfir com mensagens corretamente formatadas

2022-07-31 02:16 UTC, Math-42 approved these changes

2022-07-31 02:16 UTC, Math-42 commented on src/utils.cpp
> +    replace_all(message, ")", "]");
igualzinho do aroca jkljkljkljkl

2022-07-31 14:11 UTC, mairacanal requested changes
Destaque para "O BIPS envia um json mal formatado"

2022-07-31 14:11 UTC, mairacanal commented on src/utils.cpp
> +    }
Não é necessário esse `if` em volta

2022-07-31 14:11 UTC, mairacanal commented on src/utils.cpp
> +void replace_all(std::string& s, std::string const& toReplace, std::string const& replaceWith)
Por que essa função está em camel_case e todo resto está em PascalCase?

2022-07-31 14:11 UTC, mairacanal commented on src/utils.cpp
> +    replace_all(message, ")", "]");
Lindo!

2022-07-31 14:11 UTC, mairacanal commented on src/utils.cpp
> +    std::cout << "Wrote file: " << path << std::endl;
Vocês poderiam criar um syslog ao invés desse `cout` horroroso em todos as daemons.

2022-07-31 17:38 UTC, Grillo-0 commented on src/utils.cpp
> +    replace_all(message, ")", "]");
¯\_(ツ)_/¯

2022-07-31 17:39 UTC, Grillo-0 commented on src/utils.cpp
> +    std::cout << "Wrote file: " << path << std::endl;
Boa ideia pro fkd 2.0

2022-07-31 17:40 UTC, Grillo-0 commented on src/utils.cpp
> +void replace_all(std::string& s, std::string const& toReplace, std::string const& replaceWith)
pq eu sou burro e peguei o código do stack overflow sem olhar

2022-07-31 17:40 UTC, Grillo-0 commented on src/utils.cpp
> +void replace_all(std::string& s, std::string const& toReplace, std::string const& replaceWith)
Alias vou até botar um comentário falando que peguei de la

2022-07-31 22:07 UTC, mairacanal commented on src/utils.cpp
> +void replaceAll(std::string& s, std::string const& toReplace, std::string const& replaceWith)
I believe this is a better reference: https://thispointer.com/find-and-replace-all-occurrences-of-a-sub-string-in-c/

Check this options!

2022-08-03 17:34 UTC, mairacanal commented on src/server.cpp
> +            if (req.body.rfind("\"{\\",0) != 0) {
```suggestion
            if (!req.body.rfind("\"{\\",0)) {
```

Ultra small nit pick

2022-08-03 17:35 UTC, mairacanal requested changes

2022-08-03 17:35 UTC, mairacanal commented on src/utils.cpp
> +    // Get the first occurrence
Nossa para que tanto comentário meu deus

2022-08-03 17:37 UTC, mairacanal approved these changes
Recebi proprina para aprovar o código do jeito que tá mesmo

2022-08-03 17:46 UTC, merged