messages-buffer: make the numBytes a parameter
zenitheesc/serverd pull request #34
Opened 2022-08-01 04:14 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [X] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Adiciona uma config the tamanho de bytes, aproveitei também pra corrigir o numero de bytes pra 91

2022-08-01 11:50 UTC, mairacanal requested changes

2022-08-01 11:50 UTC, mairacanal commented on src/message-buffer.cpp
> +    std::cout << "sent message with id " << static_cast<int>(m_currIndex.front()) << std::endl;
Mudança não correlata ao commit

2022-08-01 11:50 UTC, mairacanal commented on src/server.cpp
> +    explicit ServerdService(const char* host, const int port, nlohmann::json data)
```suggestion
    explicit ServerdService(const char* host, const int port, const nlohmann::json data)
```

2022-08-01 18:33 UTC, Math-42 reviewed
No geral está muito bom, é melhor jogar tudo que for possível pra config file para não precisar ficar refazendo cross compiling todas as vezes. Só tenho os mesmos comentários que a @mairacanal.

2022-08-02 11:42 UTC, mairacanal approved these changes

2022-08-02 19:43 UTC, merged